if (typeof(window.eddata) == 'undefined') {
    console.log('EDDATA2 ::::::::::::::::::::::::::::::::: EXEC');
    /* auto generated by editiondigital :: 2023-02-02 17:55:43 GMT+0  fmdf-1v733veuh7oxd */
    window.eddata = {};
    if (typeof(window.initer) == 'undefined') {
        window.initer = {
            repairURL: function(s) {
                return s;
            }
        }
    }

    function qfp(s) {
        return ("https://d32uasgjt64yth.cloudfront.net/rq/ef.php?e=22bgsfgth&f=" + s);
    }
// adds prefix for thumbnails and page images
    function qfp_sta(s) {
        return ("https://revije.muzej.si/joker-redigitalizacija/Joker_St-18_1995-01/" + s);
    }
    window.eddata.head = {
        projectName: 'ProjectName',
        editionName: 'edition_name',
        AllPages: 64,
        pageWidth: 986,
        pageHeight: 1300,
        pageWidthHD: 1669,
        pageHeightHD: 2200,
        edition_id: 1198867586,
        edident: '22bgsfgth',
        edition_title: 'Joker 19',
        publicationLanguage: 'en',
        rtl: 0,
        stand_alone: 1,
        no_ed_cprb: 0
    };
    window.eddata.appearance = {
        edition_style: 'facingpages',
        edition_type: '2',
        edition_layout: '4',
        allowed_orientations: '1',
        pages_transition: '0',
        zoom_enabled: 1,
        loader_logo_img: 'player\/images\/ed_loader_logo_white_on_red.png',
        toolbar_logo_img: '',
        about_logo_img: 'player\/images\/edition-digital270x160.png',
        about_text: 'Edition Digital empowers creative individuals, small production teams and big publishers with a complete set of solutions for digital publishing. Creating interactive rich publications that can be published on any device has never been easier.\n<br>\n<strong>Visits us on www.editiondigital.com<\/strong>',
        about_email: '',
        follow_us_text: 'Follow us on',
        instagram_url: '',
        googleplus_url: '',
        enable_print: 0,
        sharer_email: {
            enabled: 0,
            subject: 'Here\'s something you might like: [[PAGE_TITLE]]',
            body: 'Hi!<br \/><br \/>I\'ve just stumbled upon this: [[PAGE_URL]]<br \/><br \/>I think it\'s awesome and I thought it might intrigue you as well.',
            s2f_script_url: ''
        },
        enable_sharer_facebook: 1,
        enable_sharer_twitter: 1,
        enable_sharer_whatsapp: '1',
        enable_sharer_pinterest: '1',
        enable_sharer_googleplus: 1,
        enable_sharer_linkedin: 1,
        background_color: '#222222',
        background_color_mobile: '#FFFFFF',
        toolbar_enabled: 1,
        toolbar_theme: 'dark',
        enable_panel_about_us: 1,
        enable_panel_share_and_use: 1,
        enable_panel_toc: 1,
        enable_panel_search: 0,
        enable_toc_toc: 0,
        enable_toc_pages: 1,
        background_img: '',
        background_img_scalling: 'fill',
        enable_follow_us: 1,
        api_custom_branding_js: '',
        api_custom_branding_css: '',
        cookie_policy: '',
        enable_reader_friendly: 0,
        toolbar_theme_color_1: 'rgba(51, 51, 51, 1)',
        toolbar_theme_color_2: 'rgba(70, 70, 70, 1)',
        toolbar_theme_color_3: 'rgba(221, 221, 221, 1)',
        toolbar_theme_color_4: 'rgba(221, 221, 221, 1)',
        toolbar_theme_color_5: 'rgba(221, 221, 221, 1)',
        toolbar_theme_color_6: 'rgba(0, 0, 0, 1)',
        arrow_color: 'rgba(240, 240, 240, 1)',
        arrow_bg_color: 'rgba(70,70,70,0.4)',
        subpage_indicator_color: 'rgba(118, 118, 118, 0.5)',
        subpage_indicator_active_color: 'rgba(221, 221, 221, 1)',
        additional_js: '',
        additional_css: '',
        api_policy_confirmation: '0',
        show_pdf_bookmarks: 0,
        pdf_bookmarks_title: '',
        pdf_bookmarks_multi_level_accordion_menu: 0,
        show_user_bookmarks: 0,
        show_free_annotations: 0,
        show_reading_position_indicator: 1,
        semi_facingpages: '0',
        link_style: '',
        page_transition_effect: '',
        channels: [{
            "url": "https:\/\/www.editiondigital.com",
            "name": "home",
            "title": "Home"
        }, {
            "url": "https:\/\/www.facebook.com\/EditionDigital",
            "name": "facebook",
            "title": "Facebook"
        }, {
            "url": "https:\/\/twitter.com\/editiondigital",
            "name": "twitter",
            "title": "Twitter"
        }, {
            "url": "https:\/\/www.youtube.com\/user\/editionpublisher",
            "name": "youtube",
            "title": "Youtube"
        }, {
            "url": "https:\/\/www.linkedin.com\/company\/edition-digital",
            "name": "linkedin",
            "title": "Linkedin"
        }],
        sharers: [{
            "url": "https:\/\/www.facebook.com\/dialog\/share?href=[[SHARE_URL]]&app_id=921889891312289&display=popup",
            "name": "facebook",
            "title": "Facebook"
        }, {
            "url": "http:\/\/twitter.com\/share?text=[[SHARE_TITLE]]%20via%20%40EditionDigital&url=[[SHARE_URL]]&hashtags=",
            "name": "twitter",
            "title": "Twitter"
        }, {
            "url": "https:\/\/api.whatsapp.com\/send?text=[[SHARE_TITLE]];[[SHARE_URL]]",
            "name": "whatsapp",
            "title": "WhatsApp"
        }, {
            "url": "https:\/\/www.pinterest.com\/pin\/create\/button\/?url=[[SHARE_URL]]&media=[[PAGE_IMG]]",
            "name": "pinterest",
            "title": "Pinterest"
        }, {
            "url": "https:\/\/www.linkedin.com\/shareArticle?mini=true&url=[[SHARE_URL]]&title=[[SHARE_TITLE]]",
            "name": "linkedin",
            "title": "LinkedIn"
        }],
        short_url_rq_url: 'https://request.editiondigital.com/rq/ed_page_shorturl.php?id=1198867586&gv=[[GENVER]]&pid=[[C_PAGE_ID]]'
    };
    window.eddata.ipad = {
        portrait_nop: 1,
        portrait_fit: 'CENTERED',
        landscape_nop: 2,
        landscape_fit: 'BOOK',
        locked_orientation: '',
        ed5info_only_TODO_REMOVE: 'fp-ED_EDITIONLAYOUT_SINGLE_PORTRAIT'
    };
    window.eddata.path = {
        global_path: 'https://d32uasgjt64yth.cloudfront.net/'
    };
    window.eddata.edition_templates_css = '';
    window.eddata.pages = [{
        id: 1,
        page_num_tb: '1',
        title: '',
        page_title_calc: 'Page 1',
        sef: 'page1',
        event_load: 0,
        interactive: [],
        canvas: qfp_sta("00002422_canvas.jpg"),
        thumb: qfp_sta("00002422_small_for_html5.jpg"),
        canvasHD: qfp_sta("00002422_hd.jpg"),
        tbthumb: qfp_sta("00002422_tbthumb.jpg")
    }, {
        id: 2,
        page_num_tb: '2',
        title: '',
        page_title_calc: 'Page 2',
        sef: 'page2',
        event_load: 0,
        canvas: qfp_sta("jpg/1zlzeuz2jxz00_canvas.jpg"),
        thumb: qfp_sta("jpg/1zlzeuz2jxz00_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/1zlzeuz2jxz00_hd.jpg"),
        tbthumb: qfp_sta("jpg/1zlzeuz2jxz00_tbthumb.jpg")
    }, {
        id: 3,
        page_num_tb: '3',
        title: '',
        page_title_calc: 'Page 3',
        sef: 'page3',
        event_load: 0,
        canvas: qfp_sta("jpg/07me4g4obnp60_canvas.jpg"),
        thumb: qfp_sta("jpg/07me4g4obnp60_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/07me4g4obnp60_hd.jpg"),
        tbthumb: qfp_sta("jpg/07me4g4obnp60_tbthumb.jpg")
    }, {
        id: 4,
        page_num_tb: '4',
        title: '',
        page_title_calc: 'Page 4',
        sef: 'page4',
        event_load: 0,
        canvas: qfp_sta("jpg/2uouby80z9lsl_canvas.jpg"),
        thumb: qfp_sta("jpg/2uouby80z9lsl_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2uouby80z9lsl_hd.jpg"),
        tbthumb: qfp_sta("jpg/2uouby80z9lsl_tbthumb.jpg")
    }, {
        id: 5,
        page_num_tb: '5',
        title: '',
        page_title_calc: 'Page 5',
        sef: 'page5',
        event_load: 0,
        canvas: qfp_sta("jpg/0fd1p2ocwdmct_canvas.jpg"),
        thumb: qfp_sta("jpg/0fd1p2ocwdmct_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/0fd1p2ocwdmct_hd.jpg"),
        tbthumb: qfp_sta("jpg/0fd1p2ocwdmct_tbthumb.jpg")
    }, {
        id: 6,
        page_num_tb: '6',
        title: '',
        page_title_calc: 'Page 6',
        sef: 'page6',
        event_load: 0,
        canvas: qfp_sta("jpg/3kgolhp0d6fhz_canvas.jpg"),
        thumb: qfp_sta("jpg/3kgolhp0d6fhz_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3kgolhp0d6fhz_hd.jpg"),
        tbthumb: qfp_sta("jpg/3kgolhp0d6fhz_tbthumb.jpg")
    }, {
        id: 7,
        page_num_tb: '7',
        title: '',
        page_title_calc: 'Page 7',
        sef: 'page7',
        event_load: 0,
        canvas: qfp_sta("jpg/2r3rmh08malgm_canvas.jpg"),
        thumb: qfp_sta("jpg/2r3rmh08malgm_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2r3rmh08malgm_hd.jpg"),
        tbthumb: qfp_sta("jpg/2r3rmh08malgm_tbthumb.jpg")
    }, {
        id: 8,
        page_num_tb: '8',
        title: '',
        page_title_calc: 'Page 8',
        sef: 'page8',
        event_load: 0,
        canvas: qfp_sta("jpg/29zwcoj3918m3_canvas.jpg"),
        thumb: qfp_sta("jpg/29zwcoj3918m3_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/29zwcoj3918m3_hd.jpg"),
        tbthumb: qfp_sta("jpg/29zwcoj3918m3_tbthumb.jpg")
    }, {
        id: 9,
        page_num_tb: '9',
        title: '',
        page_title_calc: 'Page 9',
        sef: 'page9',
        event_load: 0,
        canvas: qfp_sta("jpg/1c8xjscl299gb_canvas.jpg"),
        thumb: qfp_sta("jpg/1c8xjscl299gb_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/1c8xjscl299gb_hd.jpg"),
        tbthumb: qfp_sta("jpg/1c8xjscl299gb_tbthumb.jpg")
    }, {
        id: 10,
        page_num_tb: '10',
        title: '',
        page_title_calc: 'Page 10',
        sef: 'page10',
        event_load: 0,
        canvas: qfp_sta("jpg/3dvegepoxr1xt_canvas.jpg"),
        thumb: qfp_sta("jpg/3dvegepoxr1xt_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3dvegepoxr1xt_hd.jpg"),
        tbthumb: qfp_sta("jpg/3dvegepoxr1xt_tbthumb.jpg")
    }, {
        id: 11,
        page_num_tb: '11',
        title: '',
        page_title_calc: 'Page 11',
        sef: 'page11',
        event_load: 0,
        interactive: [{
            itype: 'link',
            id: 101,
            x: 119,
            y: 707,
            w: 20,
            h: 8,
            type: 'rect',
            anim_show: 'alphaset=0#alphato=100$time=0.4',
            anim_hide: '$stop=1$#$ignoreautohide=1$',
            event_click_actions: [{
                "action": "gotourl",
                "params": ["http:\/\/.se"],
                "target": ""
            }],
            dev_name: '',
            linkCssClasses: 'ed_default_linkStyle',
            linkStyle: ',nlink_000000-0-000000-0-0,nradius_0,'
        }],
        canvas: qfp_sta("jpg/1yusvj487qhrm_canvas.jpg"),
        thumb: qfp_sta("jpg/1yusvj487qhrm_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/1yusvj487qhrm_hd.jpg"),
        tbthumb: qfp_sta("jpg/1yusvj487qhrm_tbthumb.jpg")
    }, {
        id: 12,
        page_num_tb: '12',
        title: '',
        page_title_calc: 'Page 12',
        sef: 'page12',
        event_load: 0,
        canvas: qfp_sta("jpg/3iec68hc4mzgh_canvas.jpg"),
        thumb: qfp_sta("jpg/3iec68hc4mzgh_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3iec68hc4mzgh_hd.jpg"),
        tbthumb: qfp_sta("jpg/3iec68hc4mzgh_tbthumb.jpg")
    }, {
        id: 13,
        page_num_tb: '13',
        title: '',
        page_title_calc: 'Page 13',
        sef: 'page13',
        event_load: 0,
        canvas: qfp_sta("jpg/24svyf70ygxvs_canvas.jpg"),
        thumb: qfp_sta("jpg/24svyf70ygxvs_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/24svyf70ygxvs_hd.jpg"),
        tbthumb: qfp_sta("jpg/24svyf70ygxvs_tbthumb.jpg")
    }, {
        id: 14,
        page_num_tb: '14',
        title: '',
        page_title_calc: 'Page 14',
        sef: 'page14',
        event_load: 0,
        interactive: [{
            itype: 'link',
            id: 102,
            x: 122,
            y: 459,
            w: 185,
            h: 11,
            type: 'rect',
            anim_show: 'alphaset=0#alphato=100$time=0.4',
            anim_hide: '$stop=1$#$ignoreautohide=1$',
            event_click_actions: [{
                "action": "gotourl",
                "params": ["http:\/\/l^^^ž&al"],
                "target": ""
            }],
            dev_name: '',
            linkCssClasses: 'ed_default_linkStyle',
            linkStyle: ',nlink_000000-0-000000-0-0,nradius_0,'
        }],
        canvas: qfp_sta("jpg/1tapmwes1pf0n_canvas.jpg"),
        thumb: qfp_sta("jpg/1tapmwes1pf0n_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/1tapmwes1pf0n_hd.jpg"),
        tbthumb: qfp_sta("jpg/1tapmwes1pf0n_tbthumb.jpg")
    }, {
        id: 15,
        page_num_tb: '15',
        title: '',
        page_title_calc: 'Page 15',
        sef: 'page15',
        event_load: 0,
        canvas: qfp_sta("jpg/24oteyd7vcqa4_canvas.jpg"),
        thumb: qfp_sta("jpg/24oteyd7vcqa4_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/24oteyd7vcqa4_hd.jpg"),
        tbthumb: qfp_sta("jpg/24oteyd7vcqa4_tbthumb.jpg")
    }, {
        id: 16,
        page_num_tb: '16',
        title: '',
        page_title_calc: 'Page 16',
        sef: 'page16',
        event_load: 0,
        canvas: qfp_sta("jpg/3gpa544vslbx9_canvas.jpg"),
        thumb: qfp_sta("jpg/3gpa544vslbx9_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3gpa544vslbx9_hd.jpg"),
        tbthumb: qfp_sta("jpg/3gpa544vslbx9_tbthumb.jpg")
    }, {
        id: 17,
        page_num_tb: '17',
        title: '',
        page_title_calc: 'Page 17',
        sef: 'page17',
        event_load: 0,
        canvas: qfp_sta("jpg/2cgzu4gg6k1ou_canvas.jpg"),
        thumb: qfp_sta("jpg/2cgzu4gg6k1ou_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2cgzu4gg6k1ou_hd.jpg"),
        tbthumb: qfp_sta("jpg/2cgzu4gg6k1ou_tbthumb.jpg")
    }, {
        id: 18,
        page_num_tb: '18',
        title: '',
        page_title_calc: 'Page 18',
        sef: 'page18',
        event_load: 0,
        canvas: qfp_sta("jpg/3m2aqhd43i32t_canvas.jpg"),
        thumb: qfp_sta("jpg/3m2aqhd43i32t_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3m2aqhd43i32t_hd.jpg"),
        tbthumb: qfp_sta("jpg/3m2aqhd43i32t_tbthumb.jpg")
    }, {
        id: 19,
        page_num_tb: '19',
        title: '',
        page_title_calc: 'Page 19',
        sef: 'page19',
        event_load: 0,
        canvas: qfp_sta("jpg/3n2cgqb0vhzrv_canvas.jpg"),
        thumb: qfp_sta("jpg/3n2cgqb0vhzrv_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3n2cgqb0vhzrv_hd.jpg"),
        tbthumb: qfp_sta("jpg/3n2cgqb0vhzrv_tbthumb.jpg")
    }, {
        id: 20,
        page_num_tb: '20',
        title: '',
        page_title_calc: 'Page 20',
        sef: 'page20',
        event_load: 0,
        canvas: qfp_sta("jpg/2vo01emdiu465_canvas.jpg"),
        thumb: qfp_sta("jpg/2vo01emdiu465_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2vo01emdiu465_hd.jpg"),
        tbthumb: qfp_sta("jpg/2vo01emdiu465_tbthumb.jpg")
    }, {
        id: 21,
        page_num_tb: '21',
        title: '',
        page_title_calc: 'Page 21',
        sef: 'page21',
        event_load: 0,
        interactive: [{
            itype: 'link',
            id: 103,
            x: 122,
            y: 1163,
            w: 632,
            h: 86,
            type: 'rect',
            anim_show: 'alphaset=0#alphato=100$time=0.4',
            anim_hide: '$stop=1$#$ignoreautohide=1$',
            event_click_actions: [{
                "action": "gotourl",
                "params": ["http:\/\/sisteme.\r\n.......................PHILIPS -CD-"],
                "target": ""
            }],
            dev_name: '',
            linkCssClasses: 'ed_default_linkStyle',
            linkStyle: ',nlink_000000-0-000000-0-0,nradius_0,'
        }],
        canvas: qfp_sta("jpg/2lwb532qk1j3r_canvas.jpg"),
        thumb: qfp_sta("jpg/2lwb532qk1j3r_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2lwb532qk1j3r_hd.jpg"),
        tbthumb: qfp_sta("jpg/2lwb532qk1j3r_tbthumb.jpg")
    }, {
        id: 22,
        page_num_tb: '22',
        title: '',
        page_title_calc: 'Page 22',
        sef: 'page22',
        event_load: 0,
        canvas: qfp_sta("jpg/0jc2mz6t3yriv_canvas.jpg"),
        thumb: qfp_sta("jpg/0jc2mz6t3yriv_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/0jc2mz6t3yriv_hd.jpg"),
        tbthumb: qfp_sta("jpg/0jc2mz6t3yriv_tbthumb.jpg")
    }, {
        id: 23,
        page_num_tb: '23',
        title: '',
        page_title_calc: 'Page 23',
        sef: 'page23',
        event_load: 0,
        interactive: [{
            itype: 'link',
            id: 104,
            x: 949,
            y: 574,
            w: 37,
            h: 10,
            type: 'rect',
            anim_show: 'alphaset=0#alphato=100$time=0.4',
            anim_hide: '$stop=1$#$ignoreautohide=1$',
            event_click_actions: [{
                "action": "gotourl",
                "params": ["http:\/\/Vi.MM"],
                "target": ""
            }],
            dev_name: '',
            linkCssClasses: 'ed_default_linkStyle',
            linkStyle: ',nlink_000000-0-000000-0-0,nradius_0,'
        }],
        canvas: qfp_sta("jpg/3pyurif6z5yz9_canvas.jpg"),
        thumb: qfp_sta("jpg/3pyurif6z5yz9_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3pyurif6z5yz9_hd.jpg"),
        tbthumb: qfp_sta("jpg/3pyurif6z5yz9_tbthumb.jpg")
    }, {
        id: 24,
        page_num_tb: '24',
        title: '',
        page_title_calc: 'Page 24',
        sef: 'page24',
        event_load: 0,
        canvas: qfp_sta("jpg/3gl5we6zsw7lk_canvas.jpg"),
        thumb: qfp_sta("jpg/3gl5we6zsw7lk_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3gl5we6zsw7lk_hd.jpg"),
        tbthumb: qfp_sta("jpg/3gl5we6zsw7lk_tbthumb.jpg")
    }, {
        id: 25,
        page_num_tb: '25',
        title: '',
        page_title_calc: 'Page 25',
        sef: 'page25',
        event_load: 0,
        canvas: qfp_sta("jpg/3ma3j5nw3qopg_canvas.jpg"),
        thumb: qfp_sta("jpg/3ma3j5nw3qopg_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3ma3j5nw3qopg_hd.jpg"),
        tbthumb: qfp_sta("jpg/3ma3j5nw3qopg_tbthumb.jpg")
    }, {
        id: 26,
        page_num_tb: '26',
        title: '',
        page_title_calc: 'Page 26',
        sef: 'page26',
        event_load: 0,
        canvas: qfp_sta("jpg/2dsdma9pra5b0_canvas.jpg"),
        thumb: qfp_sta("jpg/2dsdma9pra5b0_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2dsdma9pra5b0_hd.jpg"),
        tbthumb: qfp_sta("jpg/2dsdma9pra5b0_tbthumb.jpg")
    }, {
        id: 27,
        page_num_tb: '27',
        title: '',
        page_title_calc: 'Page 27',
        sef: 'page27',
        event_load: 0,
        canvas: qfp_sta("jpg/2ikdc4drkmlio_canvas.jpg"),
        thumb: qfp_sta("jpg/2ikdc4drkmlio_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2ikdc4drkmlio_hd.jpg"),
        tbthumb: qfp_sta("jpg/2ikdc4drkmlio_tbthumb.jpg")
    }, {
        id: 28,
        page_num_tb: '28',
        title: '',
        page_title_calc: 'Page 28',
        sef: 'page28',
        event_load: 0,
        canvas: qfp_sta("jpg/0yrxpzncv3ln7_canvas.jpg"),
        thumb: qfp_sta("jpg/0yrxpzncv3ln7_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/0yrxpzncv3ln7_hd.jpg"),
        tbthumb: qfp_sta("jpg/0yrxpzncv3ln7_tbthumb.jpg")
    }, {
        id: 29,
        page_num_tb: '29',
        title: '',
        page_title_calc: 'Page 29',
        sef: 'page29',
        event_load: 0,
        canvas: qfp_sta("jpg/3tmnucl9m09ak_canvas.jpg"),
        thumb: qfp_sta("jpg/3tmnucl9m09ak_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3tmnucl9m09ak_hd.jpg"),
        tbthumb: qfp_sta("jpg/3tmnucl9m09ak_tbthumb.jpg")
    }, {
        id: 30,
        page_num_tb: '30',
        title: '',
        page_title_calc: 'Page 30',
        sef: 'page30',
        event_load: 0,
        canvas: qfp_sta("jpg/1gvfwenqbfnzq_canvas.jpg"),
        thumb: qfp_sta("jpg/1gvfwenqbfnzq_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/1gvfwenqbfnzq_hd.jpg"),
        tbthumb: qfp_sta("jpg/1gvfwenqbfnzq_tbthumb.jpg")
    }, {
        id: 31,
        page_num_tb: '31',
        title: '',
        page_title_calc: 'Page 31',
        sef: 'page31',
        event_load: 0,
        canvas: qfp_sta("jpg/2m311n9jasqz3_canvas.jpg"),
        thumb: qfp_sta("jpg/2m311n9jasqz3_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2m311n9jasqz3_hd.jpg"),
        tbthumb: qfp_sta("jpg/2m311n9jasqz3_tbthumb.jpg")
    }, {
        id: 32,
        page_num_tb: '32',
        title: '',
        page_title_calc: 'Page 32',
        sef: 'page32',
        event_load: 0,
        canvas: qfp_sta("jpg/0d9595a6pjm8d_canvas.jpg"),
        thumb: qfp_sta("jpg/0d9595a6pjm8d_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/0d9595a6pjm8d_hd.jpg"),
        tbthumb: qfp_sta("jpg/0d9595a6pjm8d_tbthumb.jpg")
    }, {
        id: 33,
        page_num_tb: '33',
        title: '',
        page_title_calc: 'Page 33',
        sef: 'page33',
        event_load: 0,
        canvas: qfp_sta("jpg/2susj9d61tnlg_canvas.jpg"),
        thumb: qfp_sta("jpg/2susj9d61tnlg_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2susj9d61tnlg_hd.jpg"),
        tbthumb: qfp_sta("jpg/2susj9d61tnlg_tbthumb.jpg")
    }, {
        id: 34,
        page_num_tb: '34',
        title: '',
        page_title_calc: 'Page 34',
        sef: 'page34',
        event_load: 0,
        canvas: qfp_sta("jpg/1mz7yo5krbfno_canvas.jpg"),
        thumb: qfp_sta("jpg/1mz7yo5krbfno_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/1mz7yo5krbfno_hd.jpg"),
        tbthumb: qfp_sta("jpg/1mz7yo5krbfno_tbthumb.jpg")
    }, {
        id: 35,
        page_num_tb: '35',
        title: '',
        page_title_calc: 'Page 35',
        sef: 'page35',
        event_load: 0,
        canvas: qfp_sta("jpg/3e65akq1ukg0y_canvas.jpg"),
        thumb: qfp_sta("jpg/3e65akq1ukg0y_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3e65akq1ukg0y_hd.jpg"),
        tbthumb: qfp_sta("jpg/3e65akq1ukg0y_tbthumb.jpg")
    }, {
        id: 36,
        page_num_tb: '36',
        title: '',
        page_title_calc: 'Page 36',
        sef: 'page36',
        event_load: 0,
        canvas: qfp_sta("jpg/032mnay03dhpm_canvas.jpg"),
        thumb: qfp_sta("jpg/032mnay03dhpm_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/032mnay03dhpm_hd.jpg"),
        tbthumb: qfp_sta("jpg/032mnay03dhpm_tbthumb.jpg")
    }, {
        id: 37,
        page_num_tb: '37',
        title: '',
        page_title_calc: 'Page 37',
        sef: 'page37',
        event_load: 0,
        canvas: qfp_sta("jpg/2ya1aq4bn0v55_canvas.jpg"),
        thumb: qfp_sta("jpg/2ya1aq4bn0v55_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2ya1aq4bn0v55_hd.jpg"),
        tbthumb: qfp_sta("jpg/2ya1aq4bn0v55_tbthumb.jpg")
    }, {
        id: 38,
        page_num_tb: '38',
        title: '',
        page_title_calc: 'Page 38',
        sef: 'page38',
        event_load: 0,
        canvas: qfp_sta("jpg/3oied6jipk860_canvas.jpg"),
        thumb: qfp_sta("jpg/3oied6jipk860_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3oied6jipk860_hd.jpg"),
        tbthumb: qfp_sta("jpg/3oied6jipk860_tbthumb.jpg")
    }, {
        id: 39,
        page_num_tb: '39',
        title: '',
        page_title_calc: 'Page 39',
        sef: 'page39',
        event_load: 0,
        canvas: qfp_sta("jpg/2sereu68wveye_canvas.jpg"),
        thumb: qfp_sta("jpg/2sereu68wveye_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2sereu68wveye_hd.jpg"),
        tbthumb: qfp_sta("jpg/2sereu68wveye_tbthumb.jpg")
    }, {
        id: 40,
        page_num_tb: '40',
        title: '',
        page_title_calc: 'Page 40',
        sef: 'page40',
        event_load: 0,
        canvas: qfp_sta("jpg/3jeg1g7ojie1d_canvas.jpg"),
        thumb: qfp_sta("jpg/3jeg1g7ojie1d_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3jeg1g7ojie1d_hd.jpg"),
        tbthumb: qfp_sta("jpg/3jeg1g7ojie1d_tbthumb.jpg")
    }, {
        id: 41,
        page_num_tb: '41',
        title: '',
        page_title_calc: 'Page 41',
        sef: 'page41',
        event_load: 0,
        canvas: qfp_sta("jpg/2v4gdcsi6bf49_canvas.jpg"),
        thumb: qfp_sta("jpg/2v4gdcsi6bf49_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2v4gdcsi6bf49_hd.jpg"),
        tbthumb: qfp_sta("jpg/2v4gdcsi6bf49_tbthumb.jpg")
    }, {
        id: 42,
        page_num_tb: '42',
        title: '',
        page_title_calc: 'Page 42',
        sef: 'page42',
        event_load: 0,
        canvas: qfp_sta("jpg/22yfasoq8v0y2_canvas.jpg"),
        thumb: qfp_sta("jpg/22yfasoq8v0y2_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/22yfasoq8v0y2_hd.jpg"),
        tbthumb: qfp_sta("jpg/22yfasoq8v0y2_tbthumb.jpg")
    }, {
        id: 43,
        page_num_tb: '43',
        title: '',
        page_title_calc: 'Page 43',
        sef: 'page43',
        event_load: 0,
        canvas: qfp_sta("jpg/1hqbfi739wif1_canvas.jpg"),
        thumb: qfp_sta("jpg/1hqbfi739wif1_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/1hqbfi739wif1_hd.jpg"),
        tbthumb: qfp_sta("jpg/1hqbfi739wif1_tbthumb.jpg")
    }, {
        id: 44,
        page_num_tb: '44',
        title: '',
        page_title_calc: 'Page 44',
        sef: 'page44',
        event_load: 0,
        canvas: qfp_sta("jpg/0zceg90uxz1lf_canvas.jpg"),
        thumb: qfp_sta("jpg/0zceg90uxz1lf_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/0zceg90uxz1lf_hd.jpg"),
        tbthumb: qfp_sta("jpg/0zceg90uxz1lf_tbthumb.jpg")
    }, {
        id: 45,
        page_num_tb: '45',
        title: '',
        page_title_calc: 'Page 45',
        sef: 'page45',
        event_load: 0,
        interactive: [{
            itype: 'link',
            id: 105,
            x: 264,
            y: 229,
            w: 11,
            h: 6,
            type: 'rect',
            anim_show: 'alphaset=0#alphato=100$time=0.4',
            anim_hide: '$stop=1$#$ignoreautohide=1$',
            event_click_actions: [{
                "action": "gotourl",
                "params": ["http:\/\/.na"],
                "target": ""
            }],
            dev_name: '',
            linkCssClasses: 'ed_default_linkStyle',
            linkStyle: ',nlink_000000-0-000000-0-0,nradius_0,'
        }],
        canvas: qfp_sta("jpg/1gc6vmrlle2ce_canvas.jpg"),
        thumb: qfp_sta("jpg/1gc6vmrlle2ce_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/1gc6vmrlle2ce_hd.jpg"),
        tbthumb: qfp_sta("jpg/1gc6vmrlle2ce_tbthumb.jpg")
    }, {
        id: 46,
        page_num_tb: '46',
        title: '',
        page_title_calc: 'Page 46',
        sef: 'page46',
        event_load: 0,
        canvas: qfp_sta("jpg/3gud6igtb7sih_canvas.jpg"),
        thumb: qfp_sta("jpg/3gud6igtb7sih_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3gud6igtb7sih_hd.jpg"),
        tbthumb: qfp_sta("jpg/3gud6igtb7sih_tbthumb.jpg")
    }, {
        id: 47,
        page_num_tb: '47',
        title: '',
        page_title_calc: 'Page 47',
        sef: 'page47',
        event_load: 0,
        canvas: qfp_sta("jpg/1l5wgxxuaryyx_canvas.jpg"),
        thumb: qfp_sta("jpg/1l5wgxxuaryyx_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/1l5wgxxuaryyx_hd.jpg"),
        tbthumb: qfp_sta("jpg/1l5wgxxuaryyx_tbthumb.jpg")
    }, {
        id: 48,
        page_num_tb: '48',
        title: '',
        page_title_calc: 'Page 48',
        sef: 'page48',
        event_load: 0,
        interactive: [{
            itype: 'link',
            id: 106,
            x: 452,
            y: 617,
            w: 186,
            h: 53,
            type: 'rect',
            anim_show: 'alphaset=0#alphato=100$time=0.4',
            anim_hide: '$stop=1$#$ignoreautohide=1$',
            event_click_actions: [{
                "action": "gotourl",
                "params": ["http:\/\/svetovno\r\n................v.BM"],
                "target": ""
            }],
            dev_name: '',
            linkCssClasses: 'ed_default_linkStyle',
            linkStyle: ',nlink_000000-0-000000-0-0,nradius_0,'
        }],
        canvas: qfp_sta("jpg/3c0vjj2ah0xms_canvas.jpg"),
        thumb: qfp_sta("jpg/3c0vjj2ah0xms_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3c0vjj2ah0xms_hd.jpg"),
        tbthumb: qfp_sta("jpg/3c0vjj2ah0xms_tbthumb.jpg")
    }, {
        id: 49,
        page_num_tb: '49',
        title: '',
        page_title_calc: 'Page 49',
        sef: 'page49',
        event_load: 0,
        canvas: qfp_sta("jpg/22bj2hw1t51oz_canvas.jpg"),
        thumb: qfp_sta("jpg/22bj2hw1t51oz_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/22bj2hw1t51oz_hd.jpg"),
        tbthumb: qfp_sta("jpg/22bj2hw1t51oz_tbthumb.jpg")
    }, {
        id: 50,
        page_num_tb: '50',
        title: '',
        page_title_calc: 'Page 50',
        sef: 'page50',
        event_load: 0,
        canvas: qfp_sta("jpg/233z2wl3wcmbg_canvas.jpg"),
        thumb: qfp_sta("jpg/233z2wl3wcmbg_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/233z2wl3wcmbg_hd.jpg"),
        tbthumb: qfp_sta("jpg/233z2wl3wcmbg_tbthumb.jpg")
    }, {
        id: 51,
        page_num_tb: '51',
        title: '',
        page_title_calc: 'Page 51',
        sef: 'page51',
        event_load: 0,
        canvas: qfp_sta("jpg/0li4kdls0n2yh_canvas.jpg"),
        thumb: qfp_sta("jpg/0li4kdls0n2yh_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/0li4kdls0n2yh_hd.jpg"),
        tbthumb: qfp_sta("jpg/0li4kdls0n2yh_tbthumb.jpg")
    }, {
        id: 52,
        page_num_tb: '52',
        title: '',
        page_title_calc: 'Page 52',
        sef: 'page52',
        event_load: 0,
        canvas: qfp_sta("jpg/388si33x3s20k_canvas.jpg"),
        thumb: qfp_sta("jpg/388si33x3s20k_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/388si33x3s20k_hd.jpg"),
        tbthumb: qfp_sta("jpg/388si33x3s20k_tbthumb.jpg")
    }, {
        id: 53,
        page_num_tb: '53',
        title: '',
        page_title_calc: 'Page 53',
        sef: 'page53',
        event_load: 0,
        canvas: qfp_sta("jpg/3bj9nfqm7p6tm_canvas.jpg"),
        thumb: qfp_sta("jpg/3bj9nfqm7p6tm_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3bj9nfqm7p6tm_hd.jpg"),
        tbthumb: qfp_sta("jpg/3bj9nfqm7p6tm_tbthumb.jpg")
    }, {
        id: 54,
        page_num_tb: '54',
        title: '',
        page_title_calc: 'Page 54',
        sef: 'page54',
        event_load: 0,
        canvas: qfp_sta("jpg/0zz9yct7s28yy_canvas.jpg"),
        thumb: qfp_sta("jpg/0zz9yct7s28yy_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/0zz9yct7s28yy_hd.jpg"),
        tbthumb: qfp_sta("jpg/0zz9yct7s28yy_tbthumb.jpg")
    }, {
        id: 55,
        page_num_tb: '55',
        title: '',
        page_title_calc: 'Page 55',
        sef: 'page55',
        event_load: 0,
        canvas: qfp_sta("jpg/2qtqag7qs5bgt_canvas.jpg"),
        thumb: qfp_sta("jpg/2qtqag7qs5bgt_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/2qtqag7qs5bgt_hd.jpg"),
        tbthumb: qfp_sta("jpg/2qtqag7qs5bgt_tbthumb.jpg")
    }, {
        id: 56,
        page_num_tb: '56',
        title: '',
        page_title_calc: 'Page 56',
        sef: 'page56',
        event_load: 0,
        canvas: qfp_sta("jpg/0dy5klxtnt2pg_canvas.jpg"),
        thumb: qfp_sta("jpg/0dy5klxtnt2pg_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/0dy5klxtnt2pg_hd.jpg"),
        tbthumb: qfp_sta("jpg/0dy5klxtnt2pg_tbthumb.jpg")
    }, {
        id: 57,
        page_num_tb: '57',
        title: '',
        page_title_calc: 'Page 57',
        sef: 'page57',
        event_load: 0,
        canvas: qfp_sta("jpg/1ex4akezwhvzg_canvas.jpg"),
        thumb: qfp_sta("jpg/1ex4akezwhvzg_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/1ex4akezwhvzg_hd.jpg"),
        tbthumb: qfp_sta("jpg/1ex4akezwhvzg_tbthumb.jpg")
    }, {
        id: 58,
        page_num_tb: '58',
        title: '',
        page_title_calc: 'Page 58',
        sef: 'page58',
        event_load: 0,
        canvas: qfp_sta("jpg/3jxd6kkrvl3h5_canvas.jpg"),
        thumb: qfp_sta("jpg/3jxd6kkrvl3h5_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3jxd6kkrvl3h5_hd.jpg"),
        tbthumb: qfp_sta("jpg/3jxd6kkrvl3h5_tbthumb.jpg")
    }, {
        id: 59,
        page_num_tb: '59',
        title: '',
        page_title_calc: 'Page 59',
        sef: 'page59',
        event_load: 0,
        canvas: qfp_sta("jpg/353coukcy4j53_canvas.jpg"),
        thumb: qfp_sta("jpg/353coukcy4j53_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/353coukcy4j53_hd.jpg"),
        tbthumb: qfp_sta("jpg/353coukcy4j53_tbthumb.jpg")
    }, {
        id: 60,
        page_num_tb: '60',
        title: '',
        page_title_calc: 'Page 60',
        sef: 'page60',
        event_load: 0,
        canvas: qfp_sta("jpg/3rm7lgzyciy57_canvas.jpg"),
        thumb: qfp_sta("jpg/3rm7lgzyciy57_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3rm7lgzyciy57_hd.jpg"),
        tbthumb: qfp_sta("jpg/3rm7lgzyciy57_tbthumb.jpg")
    }, {
        id: 61,
        page_num_tb: '61',
        title: '',
        page_title_calc: 'Page 61',
        sef: 'page61',
        event_load: 0,
        canvas: qfp_sta("jpg/0i4v4mo9d1315_canvas.jpg"),
        thumb: qfp_sta("jpg/0i4v4mo9d1315_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/0i4v4mo9d1315_hd.jpg"),
        tbthumb: qfp_sta("jpg/0i4v4mo9d1315_tbthumb.jpg")
    }, {
        id: 62,
        page_num_tb: '62',
        title: '',
        page_title_calc: 'Page 62',
        sef: 'page62',
        event_load: 0,
        interactive: [{
            itype: 'link',
            id: 107,
            x: 472,
            y: 179,
            w: 202,
            h: 217,
            type: 'rect',
            anim_show: 'alphaset=0#alphato=100$time=0.4',
            anim_hide: '$stop=1$#$ignoreautohide=1$',
            event_click_actions: [{
                "action": "gotourl",
                "params": ["http:\/\/SETTLERS.\r\n7\/TH"],
                "target": ""
            }],
            dev_name: '',
            linkCssClasses: 'ed_default_linkStyle',
            linkStyle: ',nlink_000000-0-000000-0-0,nradius_0,'
        }],
        canvas: qfp_sta("jpg/3ajs8my5wdrk4_canvas.jpg"),
        thumb: qfp_sta("jpg/3ajs8my5wdrk4_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3ajs8my5wdrk4_hd.jpg"),
        tbthumb: qfp_sta("jpg/3ajs8my5wdrk4_tbthumb.jpg")
    }, {
        id: 63,
        page_num_tb: '63',
        title: '',
        page_title_calc: 'Page 63',
        sef: 'page63',
        event_load: 0,
        interactive: [{
            itype: 'link',
            id: 108,
            x: 175,
            y: 342,
            w: 159,
            h: 78,
            type: 'rect',
            anim_show: 'alphaset=0#alphato=100$time=0.4',
            anim_hide: '$stop=1$#$ignoreautohide=1$',
            event_click_actions: [{
                "action": "gotourl",
                "params": ["http:\/\/i4|\r\n\/-Mh\r\n7.377.00\r\n9.430.00"],
                "target": ""
            }],
            dev_name: '',
            linkCssClasses: 'ed_default_linkStyle',
            linkStyle: ',nlink_000000-0-000000-0-0,nradius_0,'
        }],
        canvas: qfp_sta("jpg/3vqoxd8pue9qj_canvas.jpg"),
        thumb: qfp_sta("jpg/3vqoxd8pue9qj_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3vqoxd8pue9qj_hd.jpg"),
        tbthumb: qfp_sta("jpg/3vqoxd8pue9qj_tbthumb.jpg")
    }, {
        id: 64,
        page_num_tb: '64',
        title: '',
        page_title_calc: 'Page 64',
        sef: 'page64',
        event_load: 0,
        canvas: qfp_sta("jpg/3ebh20g350icw_canvas.jpg"),
        thumb: qfp_sta("jpg/3ebh20g350icw_small_for_html5.jpg"),
        canvasHD: qfp_sta("jpg/3ebh20g350icw_hd.jpg"),
        tbthumb: qfp_sta("jpg/3ebh20g350icw_tbthumb.jpg")
    }];
    window.eddata.pages_mobile = [];
    window.eddata.mobile_elements = {};
    window.eddata.pdf_bookmarks = [];
    var eddatajs_secure_ident_qqsvgniyg = 1;

    function checkAndFixedgl() {
        if ((typeof(window.edgl) == 'undefined') || (window.edgl == null)) {
            var http = window.location.protocol;
            var host = window.location.hostname;
            window.edgl = {
                argo: '',
                plversion: '',
                eddevp: '',
                xmlversion: '',
                base_path: '',
                token: '',
                ptoken: '',
                player: '',
                edition: {
                    id: -1
                }
            }
        }
    }
    checkAndFixedgl();
    if (typeof(window.eddata.textBlock) == 'undefined') {
        window.eddata.textBlock = new Array();
    }
    if (typeof(window.eddata.ipad) == 'undefined') {
        window.eddata.ipad = new Array();
    }
    if (typeof(eddata.path) == 'undefined') {
        eddata.path = {
            global_path: 'http://global_path_not_set/'
        };
    }
    window.eddata.appearance.loader_logo_img = window.eddata.appearance.loader_logo_img.replace("[[PLVERSION]]", window.edgl.plversion);
    window.eddata.appearance.about_logo_img = window.eddata.appearance.about_logo_img.replace("[[PLVERSION]]", window.edgl.plversion);
    window.eddata.appearance.loader_logo_img = window.eddata.appearance.loader_logo_img.replace("[[PLBASEPATH]]", window.edgl.base_path);
    window.eddata.appearance.about_logo_img = window.eddata.appearance.about_logo_img.replace("[[PLBASEPATH]]", window.edgl.base_path);
    if (typeof(window.eddata.appearance.search_rq_url) != 'undefined') {
        window.eddata.appearance.search_rq_url = window.eddata.appearance.search_rq_url.replace('[[GENVER]]', window.edgl.edition.gen_ver);
    }
    if (typeof(window.eddata.appearance.data_collection_rq_url) != 'undefined') {
        window.eddata.appearance.data_collection_rq_url = window.eddata.appearance.data_collection_rq_url.replace('[[GENVER]]', window.edgl.edition.gen_ver);
    }
    if (typeof(window.eddata.appearance.short_url_rq_url) != 'undefined') {
        window.eddata.appearance.short_url_rq_url = window.eddata.appearance.short_url_rq_url.replace('[[GENVER]]', window.edgl.edition.gen_ver);
    }
    if (typeof(window.eddata.appearance.sharer_email) == 'object') {
        if (typeof(window.eddata.appearance.sharer_email.s2f_script_url) != 'undefined') {
            window.eddata.appearance.sharer_email.s2f_script_url = window.eddata.appearance.sharer_email.s2f_script_url.replace('[[GENVER]]', window.edgl.edition.gen_ver);
        }
    }
    if (typeof window.eddata.head.stand_alone != "undefined" && window.eddata.head.stand_alone == 1) {
        if (typeof window.edgl.edition != "undefined") {
            window.edgl.edition.url = window.location.href.split("#")[0];
        }
        if (typeof window.edgl.edition.url != "undefined" && window.edgl.edition.url.indexOf("http") != 0) {
            if (typeof window.eddata.appearance.sharers != "undefined") {
                window.eddata.appearance.sharers = [];
            }
        }
    }
    var mainPage = 0;
    var subpagesCount = 1;
    for (var p in window.eddata.pages) {
        window.eddata.pages[p].loadedimageHD = false;
        if (typeof(window.eddata.pages[p].is_toc) == 'undefined') {
            window.eddata.pages[p].is_toc = 0;
        }
        if (typeof(window.eddata.pages[p].mob_page_id) == 'undefined') {
            window.eddata.pages[p].mob_page_id = 0;
        }
        if (typeof(window.eddata.pages[p].transition_params) == 'undefined') {
            window.eddata.pages[p].transition_params = {};
        }
        window.eddata.pages[p].is_true_title = false;
        if (typeof(window.eddata.pages[p].title) != 'undefined') {
            window.eddata.pages[p].is_true_title = (window.eddata.pages[p].title != '');
        }
        if (typeof(window.eddata.pages[p].additional_sef) == 'undefined') {
            window.eddata.pages[p].additional_sef = ['ed-pageid-' + window.eddata.pages[p].id.toString(), 'ed-pagenum-' + (parseInt(p) + 1).toString()];
        }
        window.eddata.pages[p].tabtitleoriginal = window.eddata.pages[p].page_title_calc;
        if (typeof(window.eddata.pages[p].tabtitle) == 'undefined') {
            if (window.eddata.pages[p].title != "") {
                window.eddata.pages[p].tabtitle = window.eddata.pages[p].page_title_calc + " - " + window.eddata.head.edition_title;
            } else {
                window.eddata.pages[p].title = window.eddata.pages[p].page_title_calc;
                window.eddata.pages[p].tabtitle = window.eddata.head.edition_title + " - " + window.eddata.pages[p].title;
            }
        }
        if (typeof(window.eddata.pages[p].sef) == 'undefined') {
            window.eddata.pages[p].sef = '';
        }
        if (typeof(window.eddata.pages[p].interactive) == 'undefined') {
            window.eddata.pages[p].interactive = new Array();
        } else {
            for (var io in window.eddata.pages[p].interactive) {
                if (typeof(window.eddata.pages[p].interactive[io].initially_hidden) == 'undefined') {
                    window.eddata.pages[p].interactive[io].initially_hidden = 0;
                }
                if (typeof(window.eddata.pages[p].interactive[io].anim_show) == 'undefined') {
                    window.eddata.pages[p].interactive[io].anim_show = '';
                }
                if (typeof(window.eddata.pages[p].interactive[io].anim_hide) == 'undefined') {
                    window.eddata.pages[p].interactive[io].anim_hide = '';
                }
                if (typeof(window.eddata.pages[p].interactive[io].devparam) == 'undefined') {
                    window.eddata.pages[p].interactive[io].devparam = '';
                }
                if (typeof(window.eddata.pages[p].interactive[io].dat) == 'undefined') {
                    window.eddata.pages[p].interactive[io].dat = '';
                }
                switch (window.eddata.pages[p].interactive[io].itype) {
                    case 'gallery':
                        window.eddata.pages[p].interactive[io].loaderror = false;
                        window.eddata.pages[p].interactive[io].jsobjreq = '';
                        window.eddata.pages[p].interactive[io].mid = '';
                        window.eddata.pages[p].interactive[io].sc = '';
                        window.eddata.pages[p].interactive[io].v = '';
                        if (typeof(window.eddata.pages[p].interactive[io].jsobj) != 'undefined') {
                            for (var img in window.eddata.pages[p].interactive[io].jsobj.images) {
                                if (typeof(window.eddata.pages[p].interactive[io].jsobj.images[img].title) == 'undefined') {
                                    window.eddata.pages[p].interactive[io].jsobj.images[img].title = '';
                                }
                                if (typeof(window.eddata.pages[p].interactive[io].jsobj.images[img].link) == 'undefined') {
                                    window.eddata.pages[p].interactive[io].jsobj.images[img].link = '';
                                }
                                if (typeof(window.eddata.pages[p].interactive[io].jsobj.images[img].description) == 'undefined') {
                                    window.eddata.pages[p].interactive[io].jsobj.images[img].description = '';
                                }
                            }
                        }
                        break;
                    case 'video':
                        break;
                    case 'textblock':
                        window.eddata.pages[p].interactive[io].loaderror = false;
                        window.eddata.pages[p].interactive[io].jsobjreq = '';
                        window.eddata.pages[p].interactive[io].c = '';
                        window.eddata.pages[p].interactive[io].hc = '';
                        break;
                    case 'audio':
                        break;
                    default:
                        break;
                }
            }
        }
        if (typeof(window.eddata.pages[p].links) == 'undefined') {
            window.eddata.pages[p].links = [];
        }
    }
    window.eddataloaded = 1;
    if (typeof(window.eddata.pages_mobile) == 'undefined') {
        window.eddata.pages_mobile = [];
    }
    setTimeout(function() {
        if (typeof(ed_js_ready_file) == 'function') {
            ed_js_ready_file("eddata");
        } else {
            console.log("function ed_js_ready_file not defined");
        }
    }, 100);;

}