# Generated by Django 3.0rc1 on 2019-11-21 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventura.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eksponat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(help_text='obče izdelka, ki ga eksponat predstavlja', max_length=255)),
                ('tip', models.CharField(blank=True, help_text='tovarniška oznaka, številka tipa', max_length=255, null=True)),
                ('visina_cm', models.PositiveIntegerField(verbose_name='Višina [cm]')),
                ('dolzina_cm', models.PositiveIntegerField(verbose_name='Dolžina [cm]')),
                ('sirina_cm', models.PositiveIntegerField(verbose_name='Širina [cm]')),
                ('opis', models.TextField(help_text='splošni opis izdelka, ki ga eksponat predstavlja, in se ne nanaša na specifični primerek (naj vsebuje najmanj fizični opis, po katerem je mogoče razpoznati eksponat: oblika, barva, ali je vgrajena tipkovnica, monitor, disketna enota, itd.)')),
                ('wikipedia', models.URLField(blank=True, null=True)),
                ('oldcomputers', models.URLField(blank=True, null=True)),
                ('uradnastran', models.URLField(blank=True, null=True)),
                ('vir', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Eksponati',
            },
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('opis', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Kategorije',
            },
        ),
        migrations.CreateModel(
            name='Lokacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('naslov', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Lokacije',
            },
        ),
        migrations.CreateModel(
            name='Oseba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(help_text='za fizične osebe uporabi obliko "priimek, ime"', max_length=255)),
                ('naslov', models.TextField(blank=True)),
                ('telefon', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Osebe',
            },
        ),
        migrations.CreateModel(
            name='Primerek',
            fields=[
                ('inventarna_st', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Inventarna številka')),
                ('st_delov', models.PositiveIntegerField(default=1, help_text='iz koliko delov je sestavljen primerek (vsak del ima svojo nalepko z inventarno št. in št. dela - npr. 12345/6)', verbose_name='Število delov')),
                ('serijska_st', models.CharField(blank=True, max_length=255, verbose_name='Serijska številka')),
                ('leto_proizvodnje', models.PositiveIntegerField(blank=True, null=True)),
                ('datum_inventarizacije', models.DateTimeField(auto_now_add=True)),
                ('stanje', models.TextField(blank=True, help_text='opis stanja (poškodbe, posebnosti, spremembe) in ostale opombe, specifične za ta primerek')),
                ('zgodovina', models.TextField(blank=True, help_text='zgodovina primerka (zakaj se je uporabljal, kdo in kdaj)')),
                ('vrednost', models.PositiveIntegerField(default=0, help_text='ocenjena tržna vrednost (npr Ebay), upoštevajoč stanje primerka', verbose_name='Ocenjena vrednost v USD')),
                ('polica', models.CharField(blank=True, help_text='čimbolj točna pozicija znotraj lokacije, npr: A-1.1 za prvo polico v skladišč', max_length=255, verbose_name='polica, regal')),
                ('posegi', models.TextField(blank=True, help_text='dnevnik vseh premikov, čiščenj, popravil ipd.')),
                ('donator', models.ForeignKey(blank=True, help_text='kdo je primerek podaril muzej', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventura.Oseba')),
                ('eksponat', models.ForeignKey(blank=True, help_text='pusti prazno, če gre za muzejsko opremo in ne eksponat', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventura.Eksponat')),
                ('inventariziral', models.ForeignKey(help_text='kdo je iz vhodnega dokumenta naredil kataloški vnos', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lokacija', models.ForeignKey(default=inventura.models.get_default_lokacija, on_delete=django.db.models.deletion.PROTECT, to='inventura.Lokacija')),
            ],
            options={
                'verbose_name_plural': 'Primerki',
            },
        ),
        migrations.CreateModel(
            name='Proizvajalec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('drzava', models.CharField(max_length=255, verbose_name='Država')),
                ('ustanovljen', models.PositiveIntegerField(blank=True, null=True)),
                ('propadel', models.PositiveIntegerField(blank=True, null=True)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Proizvajalci',
            },
        ),
        migrations.CreateModel(
            name='Vhod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField(help_text='kratek opis izročenih predmetov, stanje, vidne poškodbe, zgodovina predmeta')),
                ('razlog', models.CharField(choices=[('dar', 'dar'), ('izposoja', 'izposoja')], help_text='razlog za sprejem eksponata', max_length=255)),
                ('dogovorjeni_datum_vrnitve', models.DateField(blank=True, null=True)),
                ('datum_vrnitve', models.DateField(blank=True, help_text='datum dejanske vrnitve', null=True)),
                ('opombe', models.TextField(blank=True, help_text='podrobnosti glede vrnitve')),
                ('cas_prevzema', models.DateTimeField(verbose_name='čas prevzema')),
                ('izrocitelj', models.ForeignKey(blank=True, help_text='kdo je prinesel eksponat (če ni lastnik)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='izrocitelj', to='inventura.Oseba', verbose_name='izročitelj')),
                ('lastnik', models.ForeignKey(help_text='kdo je trenutno lastnik eksponata', on_delete=django.db.models.deletion.PROTECT, related_name='lastnik', to='inventura.Oseba')),
                ('prevzel', models.ForeignKey(help_text='sodelavec muzeja, ki je prevzel eksponat', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('zacasna_lokacija', models.ForeignKey(blank=True, default=inventura.models.get_default_lokacija, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventura.Lokacija', verbose_name='začasna lokacija')),
            ],
            options={
                'verbose_name_plural': 'Vhodi',
            },
        ),
        migrations.CreateModel(
            name='Razstava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('otvoritev', models.DateField()),
                ('zaključek', models.DateField()),
                ('opis', models.TextField()),
                ('avtorji', models.ManyToManyField(to='inventura.Oseba')),
                ('lokacija', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventura.Lokacija')),
                ('primerki', models.ManyToManyField(to='inventura.Primerek')),
            ],
            options={
                'verbose_name_plural': 'Razstave',
            },
        ),
        migrations.AddField(
            model_name='primerek',
            name='vhodni_dokument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventura.Vhod'),
        ),
        migrations.CreateModel(
            name='Posoja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ustanova', models.CharField(default='Posameznik', max_length=255)),
                ('stanje', models.TextField(help_text='kratek opis izročenih predmetov, stanje, vidne poškodbe')),
                ('nacin', models.TextField(help_text='Način prevzema')),
                ('namen', models.CharField(choices=[('dar', 'dar'), ('izposoja', 'izposoja')], help_text="namen posoje eksponata, npr 'razstava' ali 'popravilo'", max_length=255)),
                ('opombe', models.TextField(blank=True, help_text='podrobnosti glede vrnitve')),
                ('cas_prevzema', models.DateTimeField(verbose_name='čas prevzema')),
                ('dogovorjeni_datum_vrnitve', models.DateField(blank=True, null=True)),
                ('datum_vrnitve', models.DateField(blank=True, help_text='datum dejanske vrnitve', null=True)),
                ('izdal', models.ForeignKey(help_text='sodelavec muzeja, ki je izdal eksponat', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prevzemnik', models.ForeignKey(blank=True, help_text='komu posojamo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prevzemnik', to='inventura.Oseba', verbose_name='prevzemnik')),
                ('primerki', models.ManyToManyField(to='inventura.Primerek')),
                ('zacasna_lokacija', models.ForeignKey(blank=True, default=inventura.models.get_default_lokacija, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventura.Lokacija', verbose_name='začasna lokacija')),
            ],
            options={
                'verbose_name_plural': 'Vhodi',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVhod',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opis', models.TextField(help_text='kratek opis izročenih predmetov, stanje, vidne poškodbe, zgodovina predmeta')),
                ('razlog', models.CharField(choices=[('dar', 'dar'), ('izposoja', 'izposoja')], help_text='razlog za sprejem eksponata', max_length=255)),
                ('dogovorjeni_datum_vrnitve', models.DateField(blank=True, null=True)),
                ('datum_vrnitve', models.DateField(blank=True, help_text='datum dejanske vrnitve', null=True)),
                ('opombe', models.TextField(blank=True, help_text='podrobnosti glede vrnitve')),
                ('cas_prevzema', models.DateTimeField(verbose_name='čas prevzema')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('izrocitelj', models.ForeignKey(blank=True, db_constraint=False, help_text='kdo je prinesel eksponat (če ni lastnik)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Oseba', verbose_name='izročitelj')),
                ('lastnik', models.ForeignKey(blank=True, db_constraint=False, help_text='kdo je trenutno lastnik eksponata', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Oseba')),
                ('prevzel', models.ForeignKey(blank=True, db_constraint=False, help_text='sodelavec muzeja, ki je prevzel eksponat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zacasna_lokacija', models.ForeignKey(blank=True, db_constraint=False, default=inventura.models.get_default_lokacija, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Lokacija', verbose_name='začasna lokacija')),
            ],
            options={
                'verbose_name': 'historical vhod',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRazstava',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('otvoritev', models.DateField()),
                ('zaključek', models.DateField()),
                ('opis', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lokacija', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Lokacija')),
            ],
            options={
                'verbose_name': 'historical razstava',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrimerek',
            fields=[
                ('inventarna_st', models.PositiveIntegerField(db_index=True, verbose_name='Inventarna številka')),
                ('st_delov', models.PositiveIntegerField(default=1, help_text='iz koliko delov je sestavljen primerek (vsak del ima svojo nalepko z inventarno št. in št. dela - npr. 12345/6)', verbose_name='Število delov')),
                ('serijska_st', models.CharField(blank=True, max_length=255, verbose_name='Serijska številka')),
                ('leto_proizvodnje', models.PositiveIntegerField(blank=True, null=True)),
                ('datum_inventarizacije', models.DateTimeField(blank=True, editable=False)),
                ('stanje', models.TextField(blank=True, help_text='opis stanja (poškodbe, posebnosti, spremembe) in ostale opombe, specifične za ta primerek')),
                ('zgodovina', models.TextField(blank=True, help_text='zgodovina primerka (zakaj se je uporabljal, kdo in kdaj)')),
                ('vrednost', models.PositiveIntegerField(default=0, help_text='ocenjena tržna vrednost (npr Ebay), upoštevajoč stanje primerka', verbose_name='Ocenjena vrednost v USD')),
                ('polica', models.CharField(blank=True, help_text='čimbolj točna pozicija znotraj lokacije, npr: A-1.1 za prvo polico v skladišč', max_length=255, verbose_name='polica, regal')),
                ('posegi', models.TextField(blank=True, help_text='dnevnik vseh premikov, čiščenj, popravil ipd.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('donator', models.ForeignKey(blank=True, db_constraint=False, help_text='kdo je primerek podaril muzej', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Oseba')),
                ('eksponat', models.ForeignKey(blank=True, db_constraint=False, help_text='pusti prazno, če gre za muzejsko opremo in ne eksponat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Eksponat')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inventariziral', models.ForeignKey(blank=True, db_constraint=False, help_text='kdo je iz vhodnega dokumenta naredil kataloški vnos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lokacija', models.ForeignKey(blank=True, db_constraint=False, default=inventura.models.get_default_lokacija, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Lokacija')),
                ('vhodni_dokument', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Vhod')),
            ],
            options={
                'verbose_name': 'historical primerek',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPosoja',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ustanova', models.CharField(default='Posameznik', max_length=255)),
                ('stanje', models.TextField(help_text='kratek opis izročenih predmetov, stanje, vidne poškodbe')),
                ('nacin', models.TextField(help_text='Način prevzema')),
                ('namen', models.CharField(choices=[('dar', 'dar'), ('izposoja', 'izposoja')], help_text="namen posoje eksponata, npr 'razstava' ali 'popravilo'", max_length=255)),
                ('opombe', models.TextField(blank=True, help_text='podrobnosti glede vrnitve')),
                ('cas_prevzema', models.DateTimeField(verbose_name='čas prevzema')),
                ('dogovorjeni_datum_vrnitve', models.DateField(blank=True, null=True)),
                ('datum_vrnitve', models.DateField(blank=True, help_text='datum dejanske vrnitve', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('izdal', models.ForeignKey(blank=True, db_constraint=False, help_text='sodelavec muzeja, ki je izdal eksponat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prevzemnik', models.ForeignKey(blank=True, db_constraint=False, help_text='komu posojamo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Oseba', verbose_name='prevzemnik')),
                ('zacasna_lokacija', models.ForeignKey(blank=True, db_constraint=False, default=inventura.models.get_default_lokacija, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Lokacija', verbose_name='začasna lokacija')),
            ],
            options={
                'verbose_name': 'historical posoja',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEksponat',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ime', models.CharField(help_text='obče izdelka, ki ga eksponat predstavlja', max_length=255)),
                ('tip', models.CharField(blank=True, help_text='tovarniška oznaka, številka tipa', max_length=255, null=True)),
                ('visina_cm', models.PositiveIntegerField(verbose_name='Višina [cm]')),
                ('dolzina_cm', models.PositiveIntegerField(verbose_name='Dolžina [cm]')),
                ('sirina_cm', models.PositiveIntegerField(verbose_name='Širina [cm]')),
                ('opis', models.TextField(help_text='splošni opis izdelka, ki ga eksponat predstavlja, in se ne nanaša na specifični primerek (naj vsebuje najmanj fizični opis, po katerem je mogoče razpoznati eksponat: oblika, barva, ali je vgrajena tipkovnica, monitor, disketna enota, itd.)')),
                ('wikipedia', models.URLField(blank=True, null=True)),
                ('oldcomputers', models.URLField(blank=True, null=True)),
                ('uradnastran', models.URLField(blank=True, null=True)),
                ('vir', models.URLField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kategorija', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Kategorija')),
                ('proizvajalec', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Proizvajalec')),
            ],
            options={
                'verbose_name': 'historical eksponat',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='eksponat',
            name='kategorija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventura.Kategorija'),
        ),
        migrations.AddField(
            model_name='eksponat',
            name='proizvajalec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventura.Proizvajalec'),
        ),
    ]
