# Generated by Django 3.2.15 on 2023-02-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltiskovina',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='tiskovina',
            name='cover',
        ),
        migrations.AlterField(
            model_name='historicaltiskovina',
            name='naslovnica',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiskovina',
            name='naslovnica',
            field=models.URLField(blank=True, null=True),
        ),
    ]
