# Generated by Django 3.0rc1 on 2019-11-21 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventura.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIzhod',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ustanova', models.CharField(default='Posameznik', max_length=255)),
                ('stanje', models.TextField(help_text='kratek opis izročenih predmetov, stanje, vidne poškodbe')),
                ('nacin', models.TextField(help_text='Način prevzema')),
                ('namen', models.CharField(choices=[('dar', 'dar'), ('izposoja', 'izposoja'), ('odpis', 'odpis')], help_text="namen posoje eksponata, npr 'razstava' ali 'popravilo'", max_length=255)),
                ('opombe', models.TextField(blank=True, help_text='podrobnosti glede vrnitve')),
                ('cas_prevzema', models.DateTimeField(verbose_name='čas prevzema')),
                ('dogovorjeni_datum_vrnitve', models.DateField(blank=True, null=True)),
                ('datum_vrnitve', models.DateField(blank=True, help_text='datum dejanske vrnitve', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('izdal', models.ForeignKey(blank=True, db_constraint=False, help_text='sodelavec muzeja, ki je izdal eksponat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prevzemnik', models.ForeignKey(blank=True, db_constraint=False, help_text='komu izdajamo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Oseba', verbose_name='prevzemnik')),
                ('zacasna_lokacija', models.ForeignKey(blank=True, db_constraint=False, default=inventura.models.get_default_lokacija, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.Lokacija', verbose_name='začasna lokacija')),
            ],
            options={
                'verbose_name': 'historical izhod',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Izhod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ustanova', models.CharField(default='Posameznik', max_length=255)),
                ('stanje', models.TextField(help_text='kratek opis izročenih predmetov, stanje, vidne poškodbe')),
                ('nacin', models.TextField(help_text='Način prevzema')),
                ('namen', models.CharField(choices=[('dar', 'dar'), ('izposoja', 'izposoja'), ('odpis', 'odpis')], help_text="namen posoje eksponata, npr 'razstava' ali 'popravilo'", max_length=255)),
                ('opombe', models.TextField(blank=True, help_text='podrobnosti glede vrnitve')),
                ('cas_prevzema', models.DateTimeField(verbose_name='čas prevzema')),
                ('dogovorjeni_datum_vrnitve', models.DateField(blank=True, null=True)),
                ('datum_vrnitve', models.DateField(blank=True, help_text='datum dejanske vrnitve', null=True)),
                ('izdal', models.ForeignKey(help_text='sodelavec muzeja, ki je izdal eksponat', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prevzemnik', models.ForeignKey(blank=True, help_text='komu izdajamo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prevzemnik', to='inventura.Oseba', verbose_name='prevzemnik')),
                ('primerki', models.ManyToManyField(to='inventura.Primerek')),
                ('zacasna_lokacija', models.ForeignKey(blank=True, default=inventura.models.get_default_lokacija, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventura.Lokacija', verbose_name='začasna lokacija')),
            ],
            options={
                'verbose_name_plural': 'Izhodi',
            },
        ),
        migrations.RemoveField(
            model_name='posoja',
            name='izdal',
        ),
        migrations.RemoveField(
            model_name='posoja',
            name='prevzemnik',
        ),
        migrations.RemoveField(
            model_name='posoja',
            name='primerki',
        ),
        migrations.RemoveField(
            model_name='posoja',
            name='zacasna_lokacija',
        ),
        migrations.DeleteModel(
            name='HistoricalPosoja',
        ),
        migrations.DeleteModel(
            name='Posoja',
        ),
    ]
