# Generated by Django 3.2.15 on 2023-02-10 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventura', '0002_auto_20230204_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltiskovina',
            name='datum',
            field=models.DateField(blank=True, help_text='ce ni stevilke', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltiskovina',
            name='leto',
            field=models.IntegerField(blank=True, help_text='priporoceno', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltiskovina',
            name='mesec',
            field=models.IntegerField(blank=True, help_text='priporoceno', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltiskovina',
            name='stevilka',
            field=models.IntegerField(blank=True, help_text='ce obstaja', null=True),
        ),
        migrations.AlterField(
            model_name='tiskovina',
            name='datum',
            field=models.DateField(blank=True, help_text='ce ni stevilke', null=True),
        ),
        migrations.AlterField(
            model_name='tiskovina',
            name='leto',
            field=models.IntegerField(blank=True, help_text='priporoceno', null=True),
        ),
        migrations.AlterField(
            model_name='tiskovina',
            name='mesec',
            field=models.IntegerField(blank=True, help_text='priporoceno', null=True),
        ),
        migrations.AlterField(
            model_name='tiskovina',
            name='stevilka',
            field=models.IntegerField(blank=True, help_text='ce obstaja', null=True),
        ),
        migrations.CreateModel(
            name='Stran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.IntegerField(default=0)),
                ('ocr', models.TextField(blank=True, null=True)),
                ('cistopis', models.TextField(blank=True, null=True)),
                ('slika', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tiskovina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventura.tiskovina')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalStran',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('stevilka', models.IntegerField(default=0)),
                ('ocr', models.TextField(blank=True, null=True)),
                ('cistopis', models.TextField(blank=True, null=True)),
                ('slika', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tiskovina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventura.tiskovina')),
            ],
            options={
                'verbose_name': 'historical stran',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
