# Generated by Django 3.2.15 on 2023-02-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventura', '0003_auto_20230210_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stran',
            options={'verbose_name_plural': 'Strani'},
        ),
        migrations.AddField(
            model_name='historicalstran',
            name='vrsta',
            field=models.CharField(choices=[('vsebina', 'vsebina'), ('oglasi', 'oglasi'), ('mesano', 'mesano'), ('naslovnica', 'naslovnica'), ('kazalo', 'kazalo')], default='', help_text='Opis prevladujoce vsebine na strani', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltiskovina',
            name='dovoljenje',
            field=models.BooleanField(default=False, help_text='Ali imamo dovoljenje za spletno objavo vsebine'),
        ),
        migrations.AddField(
            model_name='stran',
            name='vrsta',
            field=models.CharField(choices=[('vsebina', 'vsebina'), ('oglasi', 'oglasi'), ('mesano', 'mesano'), ('naslovnica', 'naslovnica'), ('kazalo', 'kazalo')], default='', help_text='Opis prevladujoce vsebine na strani', max_length=255),
        ),
        migrations.AddField(
            model_name='tiskovina',
            name='dovoljenje',
            field=models.BooleanField(default=False, help_text='Ali imamo dovoljenje za spletno objavo vsebine'),
        ),
        migrations.AlterField(
            model_name='historicalstran',
            name='cistopis',
            field=models.TextField(blank=True, help_text='urednisko precisceno besedilo', null=True),
        ),
        migrations.AlterField(
            model_name='historicalstran',
            name='ocr',
            field=models.TextField(blank=True, help_text='besedilo kot smo ga pridobili iz OCR procesa', null=True),
        ),
        migrations.AlterField(
            model_name='historicalstran',
            name='slika',
            field=models.URLField(blank=True, help_text='visokoresolucijska slika strani', null=True),
        ),
        migrations.AlterField(
            model_name='stran',
            name='cistopis',
            field=models.TextField(blank=True, help_text='urednisko precisceno besedilo', null=True),
        ),
        migrations.AlterField(
            model_name='stran',
            name='ocr',
            field=models.TextField(blank=True, help_text='besedilo kot smo ga pridobili iz OCR procesa', null=True),
        ),
        migrations.AlterField(
            model_name='stran',
            name='slika',
            field=models.URLField(blank=True, help_text='visokoresolucijska slika strani', null=True),
        ),
    ]
