# Generated by Django 3.2.15 on 2023-03-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventura', '0004_auto_20230218_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstran',
            name='vrsta',
            field=models.CharField(choices=[('vsebina', 'vsebina'), ('oglasi', 'oglasi'), ('mesano', 'mesano'), ('naslovnica', 'naslovnica'), ('kazalo', 'kazalo')], default='vsebina', help_text='Opis prevladujoce vsebine na strani', max_length=255),
        ),
        migrations.AlterField(
            model_name='stran',
            name='vrsta',
            field=models.CharField(choices=[('vsebina', 'vsebina'), ('oglasi', 'oglasi'), ('mesano', 'mesano'), ('naslovnica', 'naslovnica'), ('kazalo', 'kazalo')], default='vsebina', help_text='Opis prevladujoce vsebine na strani', max_length=255),
        ),
    ]
