/* auto generated by editiondigital :: 2023-02-02 17:55:43 GMT+0  fmdf-1v733veuh7oxd */
window.eddata = {};
if (typeof(window.initer) == 'undefined') {
    window.initer = {
        repairURL: function(s) {
            return s;
        }
    }
}

function qfp(base, page, type) {
    return ("{{ location }}/" + base + page + type + '.jpg');
}

function qfp_sta(page, type) {
    var start = {{ start }}; // this is configuration of the issue
    position = start + page - 1;
    var filename = ('00000000'+position).slice(-8);
    return ("{{ location }}/" + filename + type + '.jpg');
}
window.eddata.head = {
    projectName: 'ProjectName',
    editionName: 'edition_name',
    AllPages: 64,
    pageWidth: 986,
    pageHeight: 1300,
    pageWidthHD: 1669,
    pageHeightHD: 2200,
    edition_id: 1198867586,
    edident: '22bgsfgth',
    edition_title: 'Joker 19',
    publicationLanguage: 'en',
    rtl: 0,
    stand_alone: 1,
    no_ed_cprb: 0
};
window.eddata.appearance = {
    edition_style: 'facingpages',
    edition_type: '2',
    edition_layout: '4',
    allowed_orientations: '1',
    pages_transition: '0',
    zoom_enabled: 1,
    loader_logo_img: 'player\/images\/ed_loader_logo_white_on_red.png',
    toolbar_logo_img: '',
    about_logo_img: 'player\/images\/edition-digital270x160.png',
    about_text: 'Edition Digital empowers creative individuals, small production teams and big publishers with a complete set of solutions for digital publishing. Creating interactive rich publications that can be published on any device has never been easier.\n<br>\n<strong>Visits us on www.editiondigital.com<\/strong>',
    about_email: '',
    follow_us_text: 'Follow us on',
    instagram_url: '',
    googleplus_url: '',
    enable_print: 0,
    sharer_email: {
        enabled: 0,
        subject: 'Here\'s something you might like: [[PAGE_TITLE]]',
        body: 'Hi!<br \/><br \/>I\'ve just stumbled upon this: [[PAGE_URL]]<br \/><br \/>I think it\'s awesome and I thought it might intrigue you as well.',
        s2f_script_url: ''
    },
    enable_sharer_facebook: 1,
    enable_sharer_twitter: 1,
    enable_sharer_whatsapp: '1',
    enable_sharer_pinterest: '1',
    enable_sharer_googleplus: 1,
    enable_sharer_linkedin: 1,
    background_color: '#222222',
    background_color_mobile: '#FFFFFF',
    toolbar_enabled: 1,
    toolbar_theme: 'dark',
    enable_panel_about_us: 1,
    enable_panel_share_and_use: 1,
    enable_panel_toc: 1,
    enable_panel_search: 0,
    enable_toc_toc: 0,
    enable_toc_pages: 1,
    background_img: '',
    background_img_scalling: 'fill',
    enable_follow_us: 1,
    api_custom_branding_js: '',
    api_custom_branding_css: '',
    cookie_policy: '',
    enable_reader_friendly: 0,
    toolbar_theme_color_1: 'rgba(51, 51, 51, 1)',
    toolbar_theme_color_2: 'rgba(70, 70, 70, 1)',
    toolbar_theme_color_3: 'rgba(221, 221, 221, 1)',
    toolbar_theme_color_4: 'rgba(221, 221, 221, 1)',
    toolbar_theme_color_5: 'rgba(221, 221, 221, 1)',
    toolbar_theme_color_6: 'rgba(0, 0, 0, 1)',
    arrow_color: 'rgba(240, 240, 240, 1)',
    arrow_bg_color: 'rgba(70,70,70,0.4)',
    subpage_indicator_color: 'rgba(118, 118, 118, 0.5)',
    subpage_indicator_active_color: 'rgba(221, 221, 221, 1)',
    additional_js: '',
    additional_css: '',
    api_policy_confirmation: '0',
    show_pdf_bookmarks: 0,
    pdf_bookmarks_title: '',
    pdf_bookmarks_multi_level_accordion_menu: 0,
    show_user_bookmarks: 0,
    show_free_annotations: 0,
    show_reading_position_indicator: 1,
    semi_facingpages: '0',
    link_style: '',
    page_transition_effect: '',
    channels: [
        {"url":"https:\/\/www.racunalniski-muzej.si","name":"home","title":"Home"},{"url":"https:\/\/www.facebook.com\/racunalniskimuzej","name":"facebook","title":"Facebook"},{"url":"https:\/\/twitter.com\/muzej","name":"twitter","title":"Twitter"},{"url":"https:\/\/www.youtube.com\/user\/muzej","name":"youtube","title":"Youtube"},{"url":"https:\/\/www.linkedin.com\/company\/racunalniskimuzej","name":"linkedin","title":"Linkedin"},{"url":"https:\/\/www.instagram.com\/muzej","name":"instagram","title":"Instagram"}
    ],
    sharers: [
        {"url":"https:\/\/www.facebook.com\/dialog\/share?href=[[SHARE_URL]]&app_id=921889891312289&display=popup","name":"facebook","title":"Facebook"},{"url":"http:\/\/twitter.com\/share?text=[[SHARE_TITLE]]%20via%20%40EditionDigital&url=[[SHARE_URL]]&hashtags=","name":"twitter","title":"Twitter"},{"url":"https:\/\/api.whatsapp.com\/send?text=[[SHARE_TITLE]];[[SHARE_URL]]","name":"whatsapp","title":"WhatsApp"},{"url":"https:\/\/www.pinterest.com\/pin\/create\/button\/?url=[[SHARE_URL]]&media=[[PAGE_IMG]]","name":"pinterest","title":"Pinterest"},{"url":"https:\/\/www.linkedin.com\/shareArticle?mini=true&url=[[SHARE_URL]]&title=[[SHARE_TITLE]]","name":"linkedin","title":"LinkedIn"}
    ],
    short_url_rq_url: ''
};
window.eddata.ipad = {
    portrait_nop: 1,
    portrait_fit: 'CENTERED',
    landscape_nop: 2,
    landscape_fit: 'BOOK',
    locked_orientation: '',
    ed5info_only_TODO_REMOVE: 'fp-ED_EDITIONLAYOUT_SINGLE_PORTRAIT'
};
window.eddata.path = {
    global_path: 'https://d32uasgjt64yth.cloudfront.net/'
};
window.eddata.edition_templates_css = '';
window.eddata.pages = [
    {% for i in range %}
    {
    id: {{ forloop.counter }},
    page_num_tb: '{{ forloop.counter }}',
    title: '',
    page_title_calc: 'Page {{ forloop.counter }}',
    sef: 'page{{ forloop.counter }}',
    event_load: 0,
    interactive: [],
    canvas: qfp_sta({{ forloop.counter }},"_canvas"),
    thumb: qfp_sta({{ forloop.counter }},"_small_for_html5"),
    canvasHD: qfp_sta({{ forloop.counter }},"_hd"),
    tbthumb: qfp_sta({{ forloop.counter }},"_tbthumb")
}{% if forloop.last %}{% else %},{% endif %}
    {% endfor %}
];
window.eddata.pages_mobile = [];
window.eddata.mobile_elements = {};
window.eddata.pdf_bookmarks = [];
var eddatajs_secure_ident_qqsvgniyg = 1;

function checkAndFixedgl() {
    if ((typeof(window.edgl) == 'undefined') || (window.edgl == null)) {
        var http = window.location.protocol;
        var host = window.location.hostname;
        window.edgl = {
            argo: '',
            plversion: '',
            eddevp: '',
            xmlversion: '',
            base_path: '',
            token: '',
            ptoken: '',
            player: '',
            edition: {
                id: -1
            }
        }
    }
}
checkAndFixedgl();
if (typeof(window.eddata.textBlock) == 'undefined') {
    window.eddata.textBlock = new Array();
}
if (typeof(window.eddata.ipad) == 'undefined') {
    window.eddata.ipad = new Array();
}
if (typeof(eddata.path) == 'undefined') {
    eddata.path = {
        global_path: 'http://global_path_not_set/'
    };
}
window.eddata.appearance.loader_logo_img = window.eddata.appearance.loader_logo_img.replace("[[PLVERSION]]", window.edgl.plversion);
window.eddata.appearance.about_logo_img = window.eddata.appearance.about_logo_img.replace("[[PLVERSION]]", window.edgl.plversion);
window.eddata.appearance.loader_logo_img = window.eddata.appearance.loader_logo_img.replace("[[PLBASEPATH]]", window.edgl.base_path);
window.eddata.appearance.about_logo_img = window.eddata.appearance.about_logo_img.replace("[[PLBASEPATH]]", window.edgl.base_path);
if (typeof(window.eddata.appearance.search_rq_url) != 'undefined') {
    window.eddata.appearance.search_rq_url = window.eddata.appearance.search_rq_url.replace('[[GENVER]]', window.edgl.edition.gen_ver);
}
if (typeof(window.eddata.appearance.data_collection_rq_url) != 'undefined') {
    window.eddata.appearance.data_collection_rq_url = window.eddata.appearance.data_collection_rq_url.replace('[[GENVER]]', window.edgl.edition.gen_ver);
}
if (typeof(window.eddata.appearance.short_url_rq_url) != 'undefined') {
    window.eddata.appearance.short_url_rq_url = window.eddata.appearance.short_url_rq_url.replace('[[GENVER]]', window.edgl.edition.gen_ver);
}
if (typeof(window.eddata.appearance.sharer_email) == 'object') {
    if (typeof(window.eddata.appearance.sharer_email.s2f_script_url) != 'undefined') {
        window.eddata.appearance.sharer_email.s2f_script_url = window.eddata.appearance.sharer_email.s2f_script_url.replace('[[GENVER]]', window.edgl.edition.gen_ver);
    }
}
if (typeof window.eddata.head.stand_alone != "undefined" && window.eddata.head.stand_alone == 1) {
    if (typeof window.edgl.edition != "undefined") {
        window.edgl.edition.url = window.location.href.split("#")[0];
    }
    if (typeof window.edgl.edition.url != "undefined" && window.edgl.edition.url.indexOf("http") != 0) {
        if (typeof window.eddata.appearance.sharers != "undefined") {
            window.eddata.appearance.sharers = [];
        }
    }
}
var mainPage = 0;
var subpagesCount = 1;
for (var p in window.eddata.pages) {
    window.eddata.pages[p].loadedimageHD = false;
    if (typeof(window.eddata.pages[p].is_toc) == 'undefined') {
        window.eddata.pages[p].is_toc = 0;
    }
    if (typeof(window.eddata.pages[p].mob_page_id) == 'undefined') {
        window.eddata.pages[p].mob_page_id = 0;
    }
    if (typeof(window.eddata.pages[p].transition_params) == 'undefined') {
        window.eddata.pages[p].transition_params = {};
    }
    window.eddata.pages[p].is_true_title = false;
    if (typeof(window.eddata.pages[p].title) != 'undefined') {
        window.eddata.pages[p].is_true_title = (window.eddata.pages[p].title != '');
    }
    if (typeof(window.eddata.pages[p].additional_sef) == 'undefined') {
        window.eddata.pages[p].additional_sef = ['ed-pageid-' + window.eddata.pages[p].id.toString(), 'ed-pagenum-' + (parseInt(p) + 1).toString()];
    }
    window.eddata.pages[p].tabtitleoriginal = window.eddata.pages[p].page_title_calc;
    if (typeof(window.eddata.pages[p].tabtitle) == 'undefined') {
        if (window.eddata.pages[p].title != "") {
            window.eddata.pages[p].tabtitle = window.eddata.pages[p].page_title_calc + " - " + window.eddata.head.edition_title;
        } else {
            window.eddata.pages[p].title = window.eddata.pages[p].page_title_calc;
            window.eddata.pages[p].tabtitle = window.eddata.head.edition_title + " - " + window.eddata.pages[p].title;
        }
    }
    if (typeof(window.eddata.pages[p].sef) == 'undefined') {
        window.eddata.pages[p].sef = '';
    }
    if (typeof(window.eddata.pages[p].interactive) == 'undefined') {
        window.eddata.pages[p].interactive = new Array();
    } else {
        for (var io in window.eddata.pages[p].interactive) {
            if (typeof(window.eddata.pages[p].interactive[io].initially_hidden) == 'undefined') {
                window.eddata.pages[p].interactive[io].initially_hidden = 0;
            }
            if (typeof(window.eddata.pages[p].interactive[io].anim_show) == 'undefined') {
                window.eddata.pages[p].interactive[io].anim_show = '';
            }
            if (typeof(window.eddata.pages[p].interactive[io].anim_hide) == 'undefined') {
                window.eddata.pages[p].interactive[io].anim_hide = '';
            }
            if (typeof(window.eddata.pages[p].interactive[io].devparam) == 'undefined') {
                window.eddata.pages[p].interactive[io].devparam = '';
            }
            if (typeof(window.eddata.pages[p].interactive[io].dat) == 'undefined') {
                window.eddata.pages[p].interactive[io].dat = '';
            }
            switch (window.eddata.pages[p].interactive[io].itype) {
                case 'gallery':
                    window.eddata.pages[p].interactive[io].loaderror = false;
                    window.eddata.pages[p].interactive[io].jsobjreq = '';
                    window.eddata.pages[p].interactive[io].mid = '';
                    window.eddata.pages[p].interactive[io].sc = '';
                    window.eddata.pages[p].interactive[io].v = '';
                    if (typeof(window.eddata.pages[p].interactive[io].jsobj) != 'undefined') {
                        for (var img in window.eddata.pages[p].interactive[io].jsobj.images) {
                            if (typeof(window.eddata.pages[p].interactive[io].jsobj.images[img].title) == 'undefined') {
                                window.eddata.pages[p].interactive[io].jsobj.images[img].title = '';
                            }
                            if (typeof(window.eddata.pages[p].interactive[io].jsobj.images[img].link) == 'undefined') {
                                window.eddata.pages[p].interactive[io].jsobj.images[img].link = '';
                            }
                            if (typeof(window.eddata.pages[p].interactive[io].jsobj.images[img].description) == 'undefined') {
                                window.eddata.pages[p].interactive[io].jsobj.images[img].description = '';
                            }
                        }
                    }
                    break;
                case 'video':
                    break;
                case 'textblock':
                    window.eddata.pages[p].interactive[io].loaderror = false;
                    window.eddata.pages[p].interactive[io].jsobjreq = '';
                    window.eddata.pages[p].interactive[io].c = '';
                    window.eddata.pages[p].interactive[io].hc = '';
                    break;
                case 'audio':
                    break;
                default:
                    break;
            }
        }
    }
    if (typeof(window.eddata.pages[p].links) == 'undefined') {
        window.eddata.pages[p].links = [];
    }
}
window.eddataloaded = 1;
if (typeof(window.eddata.pages_mobile) == 'undefined') {
    window.eddata.pages_mobile = [];
}
setTimeout(function() {
    if (typeof(ed_js_ready_file) == 'function') {
        ed_js_ready_file("eddata");
    } else {
        console.log("function ed_js_ready_file not defined");
    }
}, 100);;